# a =int(input("Enter number : "))
# b =int(input("Enter number : "))
# print("Number a is : ",a)
# print("Number b is : ",b)
# print("sum is : ",a+b)
# c =int(input("Enter 1st num : "))
# d =int(input("Enter 2nd num : "))
# print(" 1st num is greated than 2nd num is : ", c>d)
# print (" average Number : " , (c+d)/2)
# print( " Square of  1st Number : " , c**2)
# name = input( "Enter your name: ")
# age = int(input("Enter your age : "))
# marks = float(input("Enter your marks : "))
# print("Welcome ", name)
# print("Your Age is ", age)
# print("Your mark is ", marks)
a = float(input("Number 1 :"))
b= float(input("Number 2 : "))
sum = a+b
avg =(a+b)/2
print("Sum  = ", sum)
print("Avg  = ", avg)